[package]
name = "zenoh-issue-1052"
version = "0.1.0"
edition = "2021"

[dependencies]
console-subscriber = "0.3.0"
futures = "0.3.30"
tokio = "1.35.1"
zenoh = "=0.11.0-rc.3"
zenoh-util = "=0.11.0-rc.3"
